version: "3.8"
services:
  # RDBMS
  mariadb:
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: <password>
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - mariadb-config:/etc/mysql/conf.d
      - mariadb-data:/var/lib/mysql
  # MQTT broker
  mosquitto:
    container_name: mosquitto
    environment:
      - PUID=1000
      - GUID=1000
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    volumes:
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
  # Private cloud
  nextcloud:
    container_name: nextcloud
    environment:
      MYSQL_DATABASE: <database>
      MYSQL_USER: <username>
      MYSQL_PASSWORD: <password>
      MYSQL_HOST: <IP of NAS>
      NEXTCLOUD_ADMIN_USER: <username>
      NEXTCLOUD_ADMIN_PASSWORD: <password>
      PHP_MEMORY_LIMIT: 2048M
      PHP_UPLOAD_LIMIT: 4096M
    image: nextcloud:latest
    ports:
      - 8880:80
    restart: unless-stopped
    volumes:
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
      - nextcloud-html:/var/www/html
  # RDBMS admin tool
  phpmyadmin:
    container_name: phpmyadmin
    environment:
      PMA_HOST: <IP of NAS>
    image: phpmyadmin:latest
    ports:
      - 8088:80
    restart: unless-stopped
  # Version control system
  scmmanager:
    container_name: scmmanager
    image: cloudogu/scm-manager:latest
    ports:
      - 2222:2222
      - 8080:8080
    restart: unless-stopped
    volumes:
      - scm-config:/var/cache/scm/work
      - scm-data:/var/lib/scm
  # File synchronization
  syncthing:
    container_name: scmmanager
    environment:
      - PUID=1000
      - GUID=1000
    image: syncthing/syncthing:latest
    ports:
      - 8384:8384
      - 21027:21027/udp
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped
    volumes:
      - syncthing-data:/var/syncthing
  # Container update utility
  watchtower:
    container_name: watchtower
    environment:
      # WATCHTOWER_MONITOR_ONLY: 'true'
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: <email>
      WATCHTOWER_NOTIFICATION_EMAIL_TO: <email>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: <smtp-server>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: <smtp-server-port>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: <email>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: <password>
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  # RDBMS
  mariadb-config:
  mariadb-data:
  # MQTT broker
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
  # Private cloud
  nextcloud-config:
  nextcloud-data:
  nextcloud-html:
  # Version control system
  scm-config:
  scm-data:
  # File synchronization
  syncthing-data:
