version: "3.8"
services:
  gerbera:
    image: gerbera/gerbera:latest
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 1900:1900/udp
      - 49494:49494/tcp
    volumes:
      - gerbera-audio:/media/audio:ro
      - gerbera-config:/var/run/gerbera
      - gerbera-photo:/media/photo:ro
      - gerbera-video:/media/video:ro
volumes:
  gerbera-audio:
    driver: local
    driver_opts:
      type: "cifs"
      device: "//<IP of NAS>/music"
      o: "username=<username>,password=<password>,vers=3.0,uid=1000,gid=1000"
  gerbera-config:
  gerbera-photo:
    driver: local
    driver_opts:
      type: "cifs"
      device: "//<IP of NAS>/photos"
      o: "username=<username>,password=<password>,vers=3.0,uid=1000,gid=1000"
  gerbera-video:
    driver: local
    driver_opts:
      type: "cifs"
      device: "//<IP of NAS>/video"
      o: "username=<username>,password=<password>,vers=3.0,uid=1000,gid=1000"
