version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: <password>
    ports:
      - 3306:3306
    volumes:
      - mariadb-config:/etc/mysql/conf.d
      - mariadb-data:/var/lib/mysql
volumes:
  mariadb-config:
  mariadb-data:
