version: "3.8"
services:
  mariadb:
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD:<password>
      - UUID:1000
      - GUID:100
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - mariadb-config:/etc/mysql/conf.d
      - mariadb-data:/var/lib/mysql
volumes:
  mariadb-config:
  mariadb-data:
