version: "3.8"
services:
  cadvisor:
    container_name: cadvisor
    devices:
      - /dev/kmsg
    expose:
      - 8888
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - monitoring
    privileged: true
    ports:
      - 8005:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
networks:
  monitoring:
    driver: bridge
