version: "3.8"

networks:
  monitor-net:
    driver: bridge

volumes:
  alertmanager-data: {}
  grafana-data: {}
  prometheus-data: {}

services:
  prometheus:
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    container_name: prometheus
    environment:
      - PUID=1000
      - GUID=100
    expose:
      - 9090
    image: prom/prometheus:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitor-net
    restart: unless-stopped
    volumes:
      - /zfs01/homes/jochen/dockprom/prometheus:/etc/prometheus
      - prometheus-data:/prometheus

  alertmanager:
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    container_name: alertmanager
    environment:
      - PUID=1000
      - GUID=100
    expose:
      - 9093
    image: prom/alertmanager:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitor-net
    restart: unless-stopped
    volumes:
      - /zfs01/homes/jochen/dockprom/alertmanager:/etc/alertmanager
      - alertmanager-data:/alertmanager

  nodeexporter:
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    container_name: nodeexporter
    environment:
      - PUID=1000
      - GUID=100
    expose:
      - 9100
    image: prom/node-exporter:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitor-net
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  cadvisor:
    container_name: cadvisor
    devices:
      - /dev/kmsg:/dev/kmsg
    environment:
      - PUID=1000
      - GUID=100
    expose:
      - 8080
    image: gcr.io/cadvisor/cadvisor:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitor-net
    privileged: true
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux

  grafana:
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - PUID=1000
      - GUID=100
    expose:
      - 3000
    image: grafana/grafana:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitor-net
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - /zfs01/homes/jochen/dockprom/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - /zfs01/homes/jochen/dockprom/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  pushgateway:
    container_name: pushgateway
    environment:
      - PUID=1000
      - GUID=100
    expose:
      - 9091
    image: prom/pushgateway:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitor-net
    restart: unless-stopped

  caddy:
    container_name: caddy
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_PASSWORD_HASH=JDJhJDE0JE91S1FrN0Z0VEsyWmhrQVpON1VzdHVLSDkyWHdsN0xNbEZYdnNIZm1pb2d1blg4Y09mL0ZP
      - PUID=1000
      - GUID=100
    image: caddy:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitor-net
    ports:
      - 3000:3000
      - 9090:9090
      - 9093:9093
      - 9091:9091
    restart: unless-stopped
    volumes:
      - /zfs01/homes/jochen/dockprom/caddy:/etc/caddy
