version: "3.8"
services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: <database>
      MYSQL_USER: <username>
      MYSQL_PASSWORD: <password>
      MYSQL_HOST: <IP of NAS>
      NEXTCLOUD_ADMIN_USER: <username>
      NEXTCLOUD_ADMIN_PASSWORD: <password>
      PHP_MEMORY_LIMIT: 2048M
      PHP_UPLOAD_LIMIT: 4096M
    ports:
      - 8880:80
    volumes:
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
      - nextcloud-html:/var/www/html
volumes:
  nextcloud-config:
  nextcloud-data:
  nextcloud-html:
