version: "3.8"
services:
  scmmanager:
    image: cloudogu/scm-manager:latest
    restart: unless-stopped
    ports:
      - 2222:2222
      - 8080:8080
    volumes:
      - scm-config:/var/cache/scm/work
      - scm-data:/var/lib/scm
volumes:
  scm-config:
  scm-data:
