version: "3.8"
services:
  scmmanager:
    container_name: scmmanager
    environment:
      - PUID=1000
      - GUID=100
    image: scmmanager/scm-manager:latest
    ports:
      - 2222:2222
      - 8080:8080
    restart: unless-stopped
    volumes:
      - scm-config:/var/cache/scm/work
      - scm-data:/var/lib/scm
volumes:
  scm-config:
  scm-data:
