version: "3.8"
services:
  syncthing:
    image: syncthing/syncthing:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - GUID=1000
    ports:
      - 8384:8384
      - 21027:21027/udp
      - 22000:22000/tcp
      - 22000:22000/udp
    volumes:
      - syncthing-data:/var/syncthing
volumes:
  syncthing-data:
