version: "3.8"
services:
  watchtower:
    # Run check all 3 hours
    command: --interval 10800
    container_name: watchtower
    environment:
      # WATCHTOWER_MONITOR_ONLY: 'true'
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: <email>
      WATCHTOWER_NOTIFICATION_EMAIL_TO: <email>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: <smtp-server>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: <smtp-server-port>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: <email>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: <password>
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
